### ISSUE TITLE
Add Footer

### ISSUE THREAD

**Issue by Rupesh-Darimisetti** [Rupesh-Darimisetti/asthra-2.0#2]
Reference website: https://asthra.mailchimpsites.com/
In this align the footer in order which consists of 
- social media handles
- pages 
- copyright

**Comment by irsayvid** [comment]
Please assign me this issue

**Comment by Rupesh-Darimisetti** [comment]
I have done maximum footer responsive, if @irsayvid want to develop or improve then you can work on this issue
